from __future__ import annotations

import json
import os
import subprocess
from datetime import datetime, timedelta
from pathlib import Path

import streamlit as st


# ============================================================
# Paths and configuration
# ============================================================

ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = ROOT / "config"
SETTINGS_PATH = CONFIG_DIR / "settings.json"

VIDEO_EXTENSIONS = {".mp4", ".webm", ".mov", ".mkv", ".avi", ".m4v"}


# ============================================================
# Helpers
# ============================================================

def load_settings() -> dict:
    if not SETTINGS_PATH.exists():
        return {}

    try:
        data = json.loads(SETTINGS_PATH.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError):
        return {}


def human_file_size(size_bytes: int) -> str:
    size = float(size_bytes)

    for unit in ("B", "KB", "MB", "GB", "TB"):
        if size < 1024 or unit == "TB":
            if unit == "B":
                return f"{int(size)} B"
            return f"{size:.1f} {unit}"
        size /= 1024

    return f"{size_bytes} B"


def scan_videos(folder: Path) -> list[dict]:
    videos: list[dict] = []

    if not folder.exists() or not folder.is_dir():
        return videos

    try:
        candidates = folder.rglob("*")
    except OSError:
        return videos

    for path in candidates:
        try:
            if not path.is_file():
                continue

            if path.suffix.lower() not in VIDEO_EXTENSIONS:
                continue

            stat = path.stat()

            videos.append(
                {
                    "path": path,
                    "name": path.name,
                    "relative": str(path.relative_to(folder)),
                    "modified": datetime.fromtimestamp(stat.st_mtime),
                    "size": stat.st_size,
                }
            )

        except (OSError, ValueError):
            continue

    videos.sort(
        key=lambda item: item["modified"],
        reverse=True,
    )

    return videos


def open_in_explorer(path: Path) -> None:
    if os.name == "nt":
        subprocess.Popen(
            ["explorer", "/select,", str(path)],
            creationflags=getattr(
                subprocess,
                "CREATE_NO_WINDOW",
                0,
            ),
        )
        return

    if os.name == "posix":
        subprocess.Popen(["xdg-open", str(path.parent)])
        return

    raise RuntimeError("Opening the file location is not supported on this system.")


def matches_date_filter(modified: datetime, filter_name: str) -> bool:
    now = datetime.now()

    if filter_name == "Today":
        return modified.date() == now.date()

    if filter_name == "This week":
        return modified >= now - timedelta(days=7)

    if filter_name == "This month":
        return modified >= now - timedelta(days=30)

    return True


def delete_video(path: Path) -> None:
    path.unlink()


# ============================================================
# Page
# ============================================================

st.set_page_config(
    page_title="ComfyMax Video Gallery",
    page_icon="🎞️",
    layout="wide",
)

st.title("🎞️ Video Gallery")
st.caption(
    "Browse, play, download and manage videos generated by ComfyUI. "
    "The selected output folder and all of its subfolders are scanned automatically."
)

settings = load_settings()

saved_output_folder = str(
    settings.get("comfyui_output_folder", "")
).strip()

if "vg_delete_candidate" not in st.session_state:
    st.session_state.vg_delete_candidate = None


# ============================================================
# Output folder
# ============================================================

if not saved_output_folder:
    st.warning(
        "No ComfyUI output folder has been configured yet. "
        "Open ComfyMax Settings, set the ComfyUI output folder, "
        "and save the settings."
    )
    st.stop()

folder = Path(saved_output_folder)

with st.container(border=True):
    folder_col1, folder_col2 = st.columns([4, 1])

    with folder_col1:
        st.markdown("##### ComfyUI video folder")
        st.code(str(folder), language=None)
        st.caption("This folder and all of its subfolders are scanned automatically.")

    with folder_col2:
        if st.button(
            "🔄 Refresh gallery",
            use_container_width=True,
        ):
            st.rerun()

if not folder.exists():
    st.error(
        "The configured ComfyUI output folder does not exist. "
        "Open Settings and check the saved path."
    )
    st.stop()

if not folder.is_dir():
    st.error(
        "The configured ComfyUI output path is not a folder. "
        "Open Settings and correct it."
    )
    st.stop()


# ============================================================
# Scan
# ============================================================

if not folder or not folder.exists() or not folder.is_dir():
    st.stop()

with st.spinner("Scanning video folder…"):
    videos = scan_videos(folder)


# ============================================================
# Filters
# ============================================================

st.divider()

filter_col1, filter_col2, filter_col3 = st.columns(
    [1.5, 1, 1]
)

with filter_col1:
    search_text = st.text_input(
        "Search",
        placeholder="Search by filename or subfolder…",
    ).strip().lower()

with filter_col2:
    date_filter = st.selectbox(
        "Date",
        ["All", "Today", "This week", "This month"],
    )

with filter_col3:
    sort_order = st.selectbox(
        "Sort",
        ["Newest first", "Oldest first", "Name A–Z", "Name Z–A"],
    )


filtered_videos = []

for video in videos:
    searchable = (
        f"{video['name']} {video['relative']}"
    ).lower()

    if search_text and search_text not in searchable:
        continue

    if not matches_date_filter(
        video["modified"],
        date_filter,
    ):
        continue

    filtered_videos.append(video)


if sort_order == "Oldest first":
    filtered_videos.sort(
        key=lambda item: item["modified"]
    )
elif sort_order == "Name A–Z":
    filtered_videos.sort(
        key=lambda item: item["name"].lower()
    )
elif sort_order == "Name Z–A":
    filtered_videos.sort(
        key=lambda item: item["name"].lower(),
        reverse=True,
    )


# ============================================================
# Summary
# ============================================================

total_size = sum(
    video["size"]
    for video in filtered_videos
)

metric1, metric2, metric3 = st.columns(3)

metric1.metric(
    "Videos",
    len(filtered_videos),
)

metric2.metric(
    "Total size",
    human_file_size(total_size),
)

metric3.metric(
    "Folder",
    folder.name or str(folder),
)

if not videos:
    st.info(
        "No video files were found in this folder."
    )
    st.stop()

if not filtered_videos:
    st.info(
        "No videos match the current filters."
    )
    st.stop()


# ============================================================
# Gallery
# ============================================================

st.divider()
st.subheader("Generated videos")

columns_per_row = st.select_slider(
    "Gallery size",
    options=[2, 3, 4, 5],
    value=5,
    help=(
        "Choose how many video previews are shown per row. "
        "Four or five columns work best on desktop."
    ),
)

gallery_columns = st.columns(columns_per_row)

for index, video in enumerate(filtered_videos):
    path: Path = video["path"]

    with gallery_columns[index % columns_per_row]:
        with st.container(border=True):
            st.markdown(
                f"#### {video['name']}"
            )

            try:
                st.video(str(path))
            except Exception as exc:
                st.warning(
                    f"Preview unavailable: {exc}"
                )

            st.caption(
                f"{video['modified'].strftime('%Y-%m-%d %H:%M')} · "
                f"{human_file_size(video['size'])}"
            )

            if video["relative"] != video["name"]:
                st.caption(
                    f"📁 {video['relative']}"
                )

            try:
                video_bytes = path.read_bytes()
            except OSError:
                video_bytes = None

            action1, action2, action3 = st.columns(3)

            with action1:
                if video_bytes is not None:
                    st.download_button(
                        "⬇️",
                        data=video_bytes,
                        file_name=video["name"],
                        mime="video/mp4",
                        key=f"download_{index}_{video['relative']}",
                        help="Download video",
                        use_container_width=True,
                    )
                else:
                    st.button(
                        "⬇️",
                        disabled=True,
                        key=f"download_disabled_{index}",
                        help="Video could not be read.",
                        use_container_width=True,
                    )

            with action2:
                if st.button(
                    "📂",
                    key=f"open_{index}_{video['relative']}",
                    help="Show file in folder",
                    use_container_width=True,
                ):
                    try:
                        open_in_explorer(path)
                    except (OSError, RuntimeError) as exc:
                        st.error(str(exc))

            with action3:
                if st.button(
                    "🗑️",
                    key=f"delete_{index}_{video['relative']}",
                    help="Delete video",
                    use_container_width=True,
                ):
                    st.session_state.vg_delete_candidate = str(path)
                    st.rerun()


# ============================================================
# Delete confirmation
# ============================================================

@st.dialog("Delete video?")
def confirm_delete_dialog(video_path: str) -> None:
    candidate_path = Path(video_path)

    st.warning(
        f"Are you sure you want to permanently delete **{candidate_path.name}**?"
    )
    st.caption("This action cannot be undone.")

    confirm_col, cancel_col = st.columns(2)

    with confirm_col:
        if st.button(
            "Yes, delete",
            type="primary",
            use_container_width=True,
            key="confirm_delete_video",
        ):
            try:
                delete_video(candidate_path)
                st.session_state.vg_delete_candidate = None
                st.rerun()
            except OSError as exc:
                st.error(
                    f"Video could not be deleted: {exc}"
                )

    with cancel_col:
        if st.button(
            "Cancel",
            use_container_width=True,
            key="cancel_delete_video",
        ):
            st.session_state.vg_delete_candidate = None
            st.rerun()


delete_candidate = st.session_state.get(
    "vg_delete_candidate"
)

if delete_candidate:
    confirm_delete_dialog(delete_candidate)
